In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from time import time

from cobra.io import load_model
from cobra.io.json import load_json_model

from main import *

cobra_model = load_model("textbook")

# Load toy models created by Stefanos
# cobra_model_1 = load_json_model('toy_1.json')
# cobra_model_2 = load_json_model('toy_2.json')


df_1 = single_double_triple_deletions(cobra_model)
# df_2 = single_double_triple_deletions(cobra_model_2)

Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled

100%|████████████████████████████████████████████████████████████████| 95/95 [00:00<00:00, 583.97it/s]

Started double deletions

100%|█████████████████████████████████████████████████████████████████| 95/95 [00:08<00:00, 10.90it/s]

In [2]:
df_1['strain'] = 1
# df_2['strain'] = 2

In [3]:
# frames = [df_1, df_2]

# df = pd.concat(frames)
df = df_1
print(df.shape)

(4655, 99)

In [4]:
# How many optimal - infeasible
print(df['status'].value_counts(normalize=False), '\n')
print(df['status'].value_counts(normalize=True))

optimal       4301
infeasible     354
Name: status, dtype: int64

optimal       0.923953
infeasible    0.076047
Name: status, dtype: float64

In [5]:
df.head()

,ACALD,ACALDt,ACKr,ACONTa,ACONTb,ACt2r,ADK1,AKGDH,AKGt2r,ALCD2x,...,SUCOAS,TALA,THD2,TKT1,TKT2,TPI,id,growth,status,strain
0,0.0,0.0,0.000000,6.00725,6.00725,0.000000,0.0,5.064376,0.0,0.0,...,-5.064376e+00,1.496984,0.0,1.496984e+00,1.181498e+00,7.477382,ACALD,8.739215e-01,optimal,1
1,0.0,0.0,0.000000,6.00725,6.00725,0.000000,0.0,5.064376,0.0,0.0,...,-5.064376e+00,1.496984,0.0,1.496984e+00,1.181498e+00,7.477382,ACALDt,8.739215e-01,optimal,1
2,0.0,0.0,0.000000,6.00725,6.00725,0.000000,0.0,5.064376,0.0,0.0,...,-5.064376e+00,1.496984,0.0,1.496984e+00,1.181498e+00,7.477382,ACKr,8.739215e-01,optimal,1
3,0.0,0.0,-1.864444,0.00000,0.00000,-1.864444,0.0,0.000000,0.0,0.0,...,-5.095120e-16,0.000000,0.0,-1.283896e-19,-1.542067e-15,0.932222,ACONTa,-1.489543e-17,optimal,1
4,0.0,0.0,-1.864444,0.00000,0.00000,-1.864444,0.0,0.000000,0.0,0.0,...,-5.095120e-16,0.000000,0.0,-1.283896e-19,-1.542067e-15,0.932222,ACONTb,-1.489543e-17,optimal,1

In [6]:
print(df.shape)

(4655, 99)

In [7]:
# Save dataset to .csv
df.to_csv('ecoli_dataset.csv')

In [1]:
import pandas as pd

df = pd.read_csv('ecoli_dataset.csv', index_col=0)
df

,ACALD,ACALDt,ACKr,ACONTa,ACONTb,ACt2r,ADK1,AKGDH,AKGt2r,ALCD2x,...,SUCOAS,TALA,THD2,TKT1,TKT2,TPI,id,growth,status,strain
0,0.0,0.0,0.000000,6.007250,6.007250,0.000000,0.000000,5.064376,0.0,0.0,...,-5.064376e+00,1.496984e+00,0.00000,1.496984e+00,1.181498e+00,7.477382,ACALD,8.739215e-01,optimal,1
1,0.0,0.0,0.000000,6.007250,6.007250,0.000000,0.000000,5.064376,0.0,0.0,...,-5.064376e+00,1.496984e+00,0.00000,1.496984e+00,1.181498e+00,7.477382,ACALDt,8.739215e-01,optimal,1
2,0.0,0.0,0.000000,6.007250,6.007250,0.000000,0.000000,5.064376,0.0,0.0,...,-5.064376e+00,1.496984e+00,0.00000,1.496984e+00,1.181498e+00,7.477382,ACKr,8.739215e-01,optimal,1
3,0.0,0.0,-1.864444,0.000000,0.000000,-1.864444,0.000000,0.000000,0.0,0.0,...,-5.095120e-16,0.000000e+00,0.00000,-1.283896e-19,-1.542067e-15,0.932222,ACONTa,-1.489543e-17,optimal,1
4,0.0,0.0,-1.864444,0.000000,0.000000,-1.864444,0.000000,0.000000,0.0,0.0,...,-5.095120e-16,0.000000e+00,0.00000,-1.283896e-19,-1.542067e-15,0.932222,ACONTb,-1.489543e-17,optimal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,0.0,0.0,0.000000,0.958857,0.958857,0.000000,0.000000,0.958857,0.0,0.0,...,-9.588571e-01,2.217713e-16,0.00000,0.000000e+00,0.000000e+00,0.479429,"TKT1,TKT2",7.804784e-16,optimal,1
4556,0.0,0.0,0.000000,0.958857,0.958857,0.000000,0.000000,0.958857,0.0,0.0,...,-9.588571e-01,2.060181e-16,0.00000,0.000000e+00,2.659995e-16,0.479429,"TKT1,TPI",0.000000e+00,infeasible,1
4557,0.0,0.0,0.000000,7.294991,7.294991,0.000000,0.000000,6.359937,0.0,0.0,...,-6.359937e+00,3.128693e-01,5.69264,3.128693e-01,0.000000e+00,8.670002,"TKT2,TKT2",8.666741e-01,optimal,1
4558,0.0,0.0,0.000000,0.958857,0.958857,0.000000,0.000000,0.958857,0.0,0.0,...,-9.588571e-01,-8.769212e-17,0.00000,-4.019842e-16,0.000000e+00,0.479429,"TKT2,TPI",-3.763086e-17,infeasible,1
4559,0.0,0.0,0.000000,0.759585,0.759585,0.000000,4.607429,0.000000,0.0,0.0,...,-1.036829e-15,9.173742e+00,0.00000,9.173742e+00,8.919585e+00,0.000000,"TPI,TPI",7.040369e-01,optimal,1